import { Container, Flex } from "@chakra-ui/react";
import Head from "next/head";
import React, { useState, useEffect } from "react";
import { useRecoilValue } from "recoil";

import MiniSidebar from "./MiniSidebar";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";
import { SidebarState } from "../../atom/state";
import { userQuery } from "../../utils/data";
import { fetchToken, fetchUser } from "../../utils/fetchData";
import { client } from "../../utils/client";

const Layout = ({ children }) => {
	const sidebar = useRecoilValue(SidebarState);

	const [tokens, setTokens] = useState(null);
	const [userSanity, setUserSanity] = useState(null);
	// console.log({ userSanity });

	const fetchUserSanity = async (userId) => {
		const query = userQuery(userId);
		const [user] = await client.fetch(query);
		setUserSanity(user);
	};

	useEffect(() => {
		const t = fetchToken();
		setTokens(t);
		if (tokens) {
			const [user] = fetchUser();
			fetchUserSanity(user?.uid);
		}
	}, [tokens]);

	return (
		<>
			<Head>
				<title>Share Photo</title>
				<meta name="description" content="Generated by Khoa" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar userSanity={userSanity} />
			<Flex w="100vw">
				{sidebar && <MiniSidebar />}
				<Sidebar userSanity={userSanity} />
				<Flex direction="column" ml={["0px", "200px"]} w="100%" mt="100px">
					{children}
				</Flex>
			</Flex>
		</>
	);
};

export default Layout;
